### ISSUE TITLE
unable to get repos from free version, that hosted on bitbucket.org

### ISSUE THREAD

**Issue by v0ff4k** [at-gmbh/bitbucket-to-gitlab#3]
ttaching to migration_script
migration_script | == importing Bitbucket projects from the main namespace ==
migration_script | requesting all repos from "https://bitbucket.org" that are visible to "v0ff4k"
migration_script | Traceback (most recent call last):
migration_script |   File "./b2g.py", line 357, in <module>
migration_script |     main()
migration_script |   File "./b2g.py", line 347, in main
migration_script |     import_main_projects()
migration_script |   File "./b2g.py", line 249, in import_main_projects
migration_script |     repo_generator = BitbucketMainRepoGenerator()
migration_script |   File "./b2g.py", line 87, in __init__
migration_script |     self.projects = list(self.bitbucket.project_list())
migration_script |   File "/usr/local/lib/python3.8/site-packages/atlassian/bitbucket/base.py", line 59, in _get_paged
migration_script |     response = self.get(url, trailing=trailing, params=params, data=data, flags=flags, absolute=absolute)
migration_script |   File "/usr/local/lib/python3.8/site-packages/atlassian/rest_client.py", line 271, in get
migration_script |     response = self.request(
migration_script |   File "/usr/local/lib/python3.8/site-packages/atlassian/rest_client.py", line 225, in request
migration_script |     response = self._session.request(
migration_script |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
migration_script |     resp = self.send(prep, **send_kwargs)
migration_script |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 695, in send
migration_script |     adapter = self.get_adapter(url=request.url)
migration_script |   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 792, in get_adapter
migration_script |     raise InvalidSchema(f"No connection adapters were found for {url!r}")
migration_script | requests.exceptions.InvalidSchema: No connection adapters were found for '"https://bitbucket.org"/rest/api/2.0/projects'

**Comment by PravinKunte** [comment]
Is your issue resolved?

**Comment by v0ff4k** [comment]
Not exactly. 
i wrote script that uses bitbucket-jira to gitlab via their API. and migrate all repos, projects, and issues!

**Comment by PravinKunte** [comment]
Actually, I want to migrate all my Bitbucket repos to GitLab. Can you please provide the script that you have written.
After using your script bitbucket repos, projects and issues are migrated or not , please elaborate that as well.

**Comment by v0ff4k** [comment]
use internal service  of gitlab to migrate sources from bitbucket to gitlab(i used gitlab comunity edition) and write my own api to api migration from api.bitbucket, now atlassian to api of gitlab (go to your gitlab.site.com/help/api to see details)

Also there a lot of unworked but with nice techniques to use both APIs of atlassian and gitlab. My script was too specific(to my projects sources and issues/tasks).  As  your project, i think too. Cause need to setup not only domain and auth keys!

Also you need to config: users, attachments, comments, titles, labels, issue spend time and many many other things. Also migration was written almost year ago.  i have done it in week and after that script was rewritten to update existing issues via gitlab API!

**Comment by PravinKunte** [comment]
Thank you for your response.
can you please share your script. that script will help me .
If you have to say anything please connect me on mail.

This is my email id : pravinkunte8806@gmail.com
